language: php
sudo: false

addons:
  apt:
    packages:
      - git

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - vendor
    - $HOME/.composer/cache/files

notifications:
  email: false

env:
  global:
    - COMPOSER_OPTIONS="--no-suggest --no-interaction"
  matrix:
    - DEPENDENCIES="--prefer-lowest"
    - DEPENDENCIES=""
install:
  - phpenv config-rm xdebug.ini
  # Disable default 300 max_execution_time limit because otherwise tests may fail.
  - echo 'max_execution_time = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer global require hirak/prestissimo:^0.3.7
  - travis_retry composer update $COMPOSER_OPTIONS $DEPENDENCIES
  # Fix PHPUnit tests on PHP >= 7.2 by upgrading Guzzle to >= 6.3.0.
  # https://github.com/guzzle/guzzle/issues/1973
  - if [[ $(phpenv version-name) = "7.2" ]] && [[ "$DEPENDENCIES" = "--prefer-lowest" ]]; then composer require guzzlehttp/guzzle:^6.3.0 --update-with-dependencies $DEPENDENCIES; fi
  - composer show

script:
  # Check only changed files.
  - IFS=$'\n'; CHANGED_FILES=($(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")); unset IFS
  - EXTRA_ARGS=('--path-mode=intersection' '--' "${CHANGED_FILES[@]}")
  - composer check-style -- --using-cache=no "${EXTRA_ARGS[@]}"
  - composer analyze
  # We have to re-unable xDebug to calculate code coverage.
  - if [[ $(phpenv version-name) = "7.1" ]] && [[ "$DEPENDENCIES" = "--prefer-lowest" ]]; then phpenv config-add xdebug.ini; fi
  - composer test
  - if [[ $(phpenv version-name) = "7.1" ]] && [[ "$DEPENDENCIES" = "--prefer-lowest" ]]; then phpenv config-rm xdebug.ini; fi
  - if [[ $(phpenv version-name) = "7.1" ]] && [[ "$DEPENDENCIES" = "--prefer-lowest" ]]; then composer metrics; fi

after_success:
  - if [[ $(phpenv version-name) = "7.1" ]] && [[ "$DEPENDENCIES" = "--prefer-lowest" ]]; then bash <(curl -s https://codecov.io/bash) -f ./clover.xml; fi
